In [3]:
# this notebook implements logical xor function with internal tensorflow backprop
import numpy as np
import tensorflow as tf

X = np.array([[1.0,0.0,0.0,1.0],[0.0,0.0,1.0,1.0]],dtype=np.float32) # 2x4 matrix
Y = np.array([[1.0,0.0,1.0,0.0]],dtype=np.float32)                   # 1x4 vector
print("X: ", X)
print("Y: ", Y)

# parameters of neural net
W1 = tf.Variable(tf.random_uniform([2,2],minval=-1,maxval=1,seed=1)) # 2x2 matrix
b1 = tf.Variable([[0.0],[0.0]])                                      # 2x1 vector
W2 = tf.Variable(tf.random_uniform([1,2],minval=-1,maxval=1,seed=1)) # 1x2 vector
b2 = tf.Variable(0.0)                                                # scalar

# computational graph
Z1 = tf.matmul(W1,X)   # 2x4 matrix
Z2 = Z1 + b1           # 2x4 matrix
Z3 = tf.nn.sigmoid(Z2) # 2x4 matrix
Z4 = tf.matmul(W2,Z3)  # 1x4 vector
Z5 = Z4 + b2           # 1x4 vector
Yp = tf.nn.sigmoid(Z5) # 1x4 vector

# init node for variable initialization
init = tf.global_variables_initializer()

# square loss function
l2loss = tf.reduce_mean(tf.square(Yp-Y))

# tensorflow optimizer
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 10)

# training operator
training_op = optimizer.minimize(l2loss)

with tf.Session() as sess:
    sess.run(init)
    for epoch in range(1000):
        if epoch==0: # just to see the computational graph at the beginning 
            W1_val = W1.eval()
            b1_val = b1.eval()
            W2_val = W2.eval()
            b2_val = b2.eval()
            Z1_val = Z1.eval()
            Z2_val = Z2.eval()
            Z3_val = Z3.eval()
            Z4_val = Z4.eval()
            Z5_val = Z5.eval()
            Yp_val = Yp.eval()
            error = l2loss.eval()
            print("W1: ",W1_val)
            print("Z1: ",Z1_val)
            print("b1: ",b1_val)
            print("Z2: ",Z2_val)
            print("Z3: ",Z3_val)
            print("W2: ",W2_val)
            print("Z4: ",Z4_val)
            print("b2: ",b2_val)
            print("Z5: ",Z5_val)            
            print("Yp: ",Yp_val)
            print("L2Loss: ",error)
        sess.run(training_op)
        if epoch%100 == 0:
            error = l2loss.eval()
            print(error)
    out = Yp.eval()
    print(out)


X:  [[ 1.  0.  0.  1.]
 [ 0.  0.  1.  1.]]
Y:  [[ 1.  0.  1.  0.]]
W1:  [[-0.52192521  0.84079909]
 [-0.89897513 -0.00851107]]
Z1:  [[-0.52192521  0.          0.84079909  0.31887388]
 [-0.89897513  0.         -0.00851107 -0.9074862 ]]
b1:  [[ 0.]
 [ 0.]]
Z2:  [[-0.52192521  0.          0.84079909  0.31887388]
 [-0.89897513  0.         -0.00851107 -0.9074862 ]]
Z3:  [[ 0.37240219  0.5         0.69863349  0.57904977]
 [ 0.28926116  0.5         0.49787226  0.28751451]]
W2:  [[-0.52192521  0.84079909]]
Z4:  [[ 0.04884443  0.15943694  0.05397612 -0.06047873]]
b2:  0.0
Z5:  [[ 0.04884443  0.15943694  0.05397612 -0.06047873]]
Yp:  [[ 0.5122087   0.53977501  0.51349074  0.48488492]]
L2Loss:  0.250275
0.25012
0.00813723
0.00221489
0.00123446
0.000846501
0.00064096
0.000514356
0.000428803
0.000367241
0.000320883
[[ 0.98069853  0.01698895  0.98405659  0.01499737]]
